### ISSUE TITLE
Save config to flash

### ISSUE THREAD

**Issue by neilenns** [neilenns/MobiFlight-STM32Firmware#10]

**Comment by danecreekphotography** [comment]
So far this hack works. Next things:

1. Update flash writing so it doesn't use a sector sized buffer. Use a smaller config buffer that's a multiple of the page size, write that, then write 0x00 for the rest of the sector in a loop.
2. Write "MF" first, then the firmware version number, for future proofing/settings upgrade support.
3. Actually write out all the attached configs.

**Comment by danecreekphotography** [comment]
std::vector<> is the key to getting the configs all in a line. Just use a vector and do insert() of std::strings? Then resize it to a multiple of the page size.

**Comment by neilenns** [comment]
This is done!
